# Generated by Django 3.2.3 on 2021-05-26 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Sell',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
