# Generated by Django 3.2.3 on 2021-05-28 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_imagep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagep',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='imagep',
            name='image2',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='imagep',
            name='image3',
            field=models.ImageField(blank=True, upload_to='products/'),
        ),
    ]
